
DOMAIN = "energie_impuls"
LOGIN_URL = "https://energie-impuls.site/api/auth/login"
DATA_URL = "https://energie-impuls.site/api/c/devices/flow/"
WALLBOX_URL = "https://energie-impuls.site/api/c/devices/wallbox/?nested=true"
WALLBOX_SETPOINT_URL = "https://energie-impuls.site/api/c/devices/wallbox/setpoint/706"
USER_ID = "user_id"
CONF_WB_DEVICE_ID = "wb_device_id"
CONF_WB_DEVICE_NAME = "wb_device_name"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_SESSION = "session"
