name: Update manifest.json version

on:
  push:
    tags:
      - "v*"

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update manifest.json
        run: |
          jq --arg version "$TAG_VERSION" '.version = $version' custom_components/energie_impuls/manifest.json > tmp.json && mv tmp.json custom_components/energie_impuls/manifest.json

      - name: Commit and push manifest change
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Set version to $TAG_VERSION in manifest.json"
          git push
